services:
  # 1. THE DATABASE
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: financetracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. THE BACKEND
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=financetracker
    depends_on:
      - db

  # 3. THE FRONTEND
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
